name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test
    - name: Run clippy
      run: cargo clippy

  build:
    runs-on: ubuntu-latest
    needs: test-and-lint

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build
